"""initial

Revision ID: 8f6ece4a8642
Revises: 
Create Date: 2026-07-09 19:13:22.206728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6ece4a8642'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('allocation_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.Column('target_pct', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_class')
    )
    op.create_table('api_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service')
    )
    op.create_index('idx_api_connections_user', 'api_connections', ['user_id'], unique=False)
    op.create_table('debts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('debt_type', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('minimum_payment', sa.Float(), nullable=False),
    sa.Column('extra_payment', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_debts_user', 'debts', ['user_id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('asset_class', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker')
    )
    op.create_index('idx_holdings_user', 'holdings', ['user_id'], unique=False)
    op.create_table('memory_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_agent', 'memory_nodes', ['agent_type'], unique=False)
    op.create_index('idx_memory_user', 'memory_nodes', ['user_id'], unique=False)
    op.create_index('idx_memory_user_type', 'memory_nodes', ['user_id', 'node_type'], unique=False)
    op.create_table('payoff_strategies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('monthly_budget', sa.Float(), nullable=False),
    sa.Column('projected_payoff_date', sa.Text(), nullable=True),
    sa.Column('total_interest_saved', sa.Float(), nullable=True),
    sa.Column('strategy_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payoff_user', 'payoff_strategies', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('alternatives', sa.Text(), nullable=True),
    sa.Column('before_state', sa.Text(), nullable=True),
    sa.Column('after_state', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recs_agent', 'recommendations', ['agent_type'], unique=False)
    op.create_index('idx_recs_user', 'recommendations', ['user_id'], unique=False)
    op.create_index('idx_recs_user_status', 'recommendations', ['user_id', 'status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('revoked', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_tokens_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('retirement_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_age', sa.Integer(), nullable=False),
    sa.Column('retirement_age', sa.Integer(), nullable=False),
    sa.Column('current_savings', sa.Float(), nullable=False),
    sa.Column('annual_income', sa.Float(), nullable=False),
    sa.Column('contribution_rate', sa.Float(), nullable=False),
    sa.Column('employer_match', sa.Float(), nullable=True),
    sa.Column('desired_income', sa.Float(), nullable=False),
    sa.Column('assumed_return', sa.Float(), nullable=False),
    sa.Column('inflation_rate', sa.Float(), nullable=False),
    sa.Column('social_security', sa.Float(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retirement_user', 'retirement_profiles', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope')
    )
    op.create_index('idx_settings_user', 'settings', ['user_id'], unique=False)
    op.create_table('execution_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.Text(), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('impact_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exec_log_rec', 'execution_log', ['recommendation_id'], unique=False)
    op.create_index('idx_exec_log_user', 'execution_log', ['user_id'], unique=False)
    op.create_table('memory_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_node_id', sa.String(length=36), nullable=False),
    sa.Column('target_node_id', sa.String(length=36), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['memory_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['memory_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_node_id', 'target_node_id', 'edge_type')
    )
    op.create_index('idx_edges_source', 'memory_edges', ['source_node_id'], unique=False)
    op.create_index('idx_edges_target', 'memory_edges', ['target_node_id'], unique=False)
    op.create_table('payment_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('debt_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Text(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_log_debt', 'payment_log', ['debt_id'], unique=False)
    op.create_index('idx_payment_log_user', 'payment_log', ['user_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('vote', sa.String(length=10), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recommendation_id')
    )
    op.create_index('idx_votes_rec', 'votes', ['recommendation_id'], unique=False)
    op.create_index('idx_votes_user', 'votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_votes_user', table_name='votes')
    op.drop_index('idx_votes_rec', table_name='votes')
    op.drop_table('votes')
    op.drop_index('idx_payment_log_user', table_name='payment_log')
    op.drop_index('idx_payment_log_debt', table_name='payment_log')
    op.drop_table('payment_log')
    op.drop_index('idx_edges_target', table_name='memory_edges')
    op.drop_index('idx_edges_source', table_name='memory_edges')
    op.drop_table('memory_edges')
    op.drop_index('idx_exec_log_user', table_name='execution_log')
    op.drop_index('idx_exec_log_rec', table_name='execution_log')
    op.drop_table('execution_log')
    op.drop_index('idx_settings_user', table_name='settings')
    op.drop_table('settings')
    op.drop_index('idx_retirement_user', table_name='retirement_profiles')
    op.drop_table('retirement_profiles')
    op.drop_index('idx_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_recs_user_status', table_name='recommendations')
    op.drop_index('idx_recs_user', table_name='recommendations')
    op.drop_index('idx_recs_agent', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('idx_payoff_user', table_name='payoff_strategies')
    op.drop_table('payoff_strategies')
    op.drop_index('idx_memory_user_type', table_name='memory_nodes')
    op.drop_index('idx_memory_user', table_name='memory_nodes')
    op.drop_index('idx_memory_agent', table_name='memory_nodes')
    op.drop_table('memory_nodes')
    op.drop_index('idx_holdings_user', table_name='holdings')
    op.drop_table('holdings')
    op.drop_index('idx_debts_user', table_name='debts')
    op.drop_table('debts')
    op.drop_index('idx_api_connections_user', table_name='api_connections')
    op.drop_table('api_connections')
    op.drop_table('allocation_targets')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
